[package]
name = "location_history"
version = "0.1.0"
authors = ["Eric Trombly <etrombly@yahoo.com>"]
repository = "https://github.com/etrombly/location_history.git"
homepage = "https://github.com/etrombly/location_history.git"
license = "MIT"
readme = "README.md"
description = "Parse google LocationHistory.json"

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = { version = "0.4", features = ["serde"] }
