[package]
authors = ["Eric Trombly <etrombly@yahoo.com>"]
description = "Parse Google LocationHistory.json"
homepage = "https://github.com/etrombly/location_history.git"
license = "MIT"
name = "location_history"
readme = "README.md"
repository = "https://github.com/etrombly/location_history.git"
version = "0.1.0"

[dependencies]
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"

[dependencies.chrono]
features = ["serde"]
version = "0.4.0"
