[package]
name = "location_history"
version = "0.1.0"
authors = ["Eric Trombly <etrombly@yahoo.com>"]

[dependencies]
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
chrono = { version = "0.3", features = ["serde"] }
